# Generated by Django 4.1.3 on 2022-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
